=begin
#OpsGenie REST API

#OpsGenie OpenAPI Specification

OpenAPI spec version: 2.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpsgenieClient::ActionMapping
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ActionMapping' do
  before do
    # run before each test
    @instance = OpsgenieClient::ActionMapping.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ActionMapping' do
    it 'should create an instance of ActionMapping' do
      expect(@instance).to be_instance_of(OpsgenieClient::ActionMapping)
    end
  end
  describe 'test attribute "action"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
       #validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["create", "acknowledge", "unacknowledge", "snooze", "escalate-to-next", "add-note", "add-recipient", "add-team", "add-tags", "remove-tags", "close", "delete", "escalate", "custom-action", "assign-ownership", "take-ownership"])
       #validator.allowable_values.each do |value|
       #  expect { @instance.action = value }.not_to raise_error
       #end
    end
  end

  describe 'test attribute "extra_field"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "extra_field_for_mapped_action"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "mapped_action"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
       #validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["publish", "create-issue", "add-comment-to-issue", "in-progress-issue", "resolve-issue", "close-issue", "issue-done", "add-note", "add-tag", "create-conversation", "set-status-to-open", "set-status-to-pending", "set-status-to-completed", "send-to-channel", "acknowledge", "create-alert", "close-alert", "acknowledge-alert", "unacknowledge-alert", "create-incident", "add-note-to-incident", "resolve-incident", "close-incident", "assign-to-group", "assign-to-user", "assign-to-owner", "send-to-custom-endpoint", "create-incident-and-update-component-statuses", "resolve-incident-and-update-component-statuses-back-to-operational", "update-component-statuses", "create-ticket", "add-internal-note", "public-reply", "set-status-to-closed", "set-status-to-solved"])
       #validator.allowable_values.each do |value|
       #  expect { @instance.mapped_action = value }.not_to raise_error
       #end
    end
  end

end

