=begin
#OpsGenie REST API

#OpsGenie OpenAPI Specification

OpenAPI spec version: 2.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpsgenieClient::AlertFilter
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'AlertFilter' do
  before do
    # run before each test
    @instance = OpsgenieClient::AlertFilter.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AlertFilter' do
    it 'should create an instance of AlertFilter' do
      expect(@instance).to be_instance_of(OpsgenieClient::AlertFilter)
    end
  end
  describe 'test attribute "condition_match_type"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
       #validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["match-all", "match-any-condition", "match-all-conditions"])
       #validator.allowable_values.each do |value|
       #  expect { @instance.condition_match_type = value }.not_to raise_error
       #end
    end
  end

  describe 'test attribute "conditions"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end

