=begin
#OpsGenie REST API

#OpsGenie OpenAPI Specification

OpenAPI spec version: 2.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpsgenieClient::GetNotificationRuleStepResponse
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'GetNotificationRuleStepResponse' do
  before do
    # run before each test
    @instance = OpsgenieClient::GetNotificationRuleStepResponse.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of GetNotificationRuleStepResponse' do
    it 'should create an instance of GetNotificationRuleStepResponse' do
      expect(@instance).to be_instance_of(OpsgenieClient::GetNotificationRuleStepResponse)
    end
  end
  describe 'test attribute "request_id"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "took"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "data"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end

